traversability_estimation:
  ros__parameters:
    traversability_map_filters:
      filter1:
          name: surfaceNormalsFilter
          type: gridMapFilters/NormalVectorsFilter
          params:
            input_layer: elevation
            output_layers_prefix: surface_normal_
            radius: 0.15
            normal_vector_positive_axis: z
      filter2:
        name: slopeFilter
        type: traversabilityFilters/SlopeFilter
        params:
          map_type: traversability_slope
          critical_value: 0.8
      filter3:
        name: stepFilter
        type: traversabilityFilters/StepFilter
        params:
          map_type: traversability_step
          critical_value: 0.12
          first_window_radius: 0.04
          second_window_radius: 0.04
          critical_cell_number: 4
      filter4:
        name: roughnessFilter
        type: traversabilityFilters/RoughnessFilter
        params:
          map_type: traversability_roughness
          critical_value: 0.2
          estimation_radius: 0.15
      filter5:
        name: weightedSumFilter
        type: gridMapFilters/MathExpressionFilter
        params:
          output_layer: traversability
          expression: (1.0 / 10.0) * (9 * traversability_slope +  1 * traversability_roughness)
      filter6:
          name: deletionFilter
          type: gridMapFilters/DeletionFilter
          params:
           layers: [surface_normal_x, surface_normal_y, surface_normal_z]
      
